- derecho/experiments/ssd_bw_test.cpp
In our cluster, `ssd_bw_test ` loops infinitely at [line 172](https://github.com/Derecho-Project/derecho-unified/blob/master/derecho/experiments/ssd_bw_test.cpp#L172) becasue the compiler may have optimized the `done` variable.
> add volatile to 'done'

- objectstore/ObjectStore.cpp
- objectstore/ObjectStore.hpp
- objectstore/performance.cpp
`leave(bool grace = true)` now supports graceful leave.
> graceful leave for objstore

- src/applications/tests/performance_tests/typed_subgroup_bw_test.cpp
I now changed it such that I use the std::pair function in aggregate_bandwidth for typed subgroup test for meaning the average latency and bandwidth.
> Now using TwoResultsSST from aggregate_bw

- include/derecho/conf/conf.hpp
- include/derecho/core/detail/external_group_impl.hpp
- include/derecho/core/detail/p2p_connection_manager.hpp
- include/derecho/core/detail/rpc_manager.hpp
- include/derecho/core/external_group.hpp
- src/conf/conf.cpp
- src/conf/derecho-sample.cfg
- src/core/git_version.cpp
- src/core/p2p_connection_manager.cpp
- src/core/rpc_manager.cpp
As discussed in the issue report for #195, the "one big lock" on P2PConnectionsManager within RPCManager was vulnerable to deadlocks. One solution is to make the P2P connections a fixed-size array with a separate lock for each P2P connection, so that unrelated add and remove operations don't block each other. I've implemented that solution and tested it to ensure P2P requests still work in normal operation. When merged, this should fix #195.
> Replaced p2p_connections_mutex with fine-grained locking

- include/derecho/rdmc/detail/lf_helper.hpp
- scripts/prerequisites/install-libfabric.sh
- src/rdmc/lf_helper.cpp
- src/rdmc/rdmc.cpp
- src/sst/lf.cpp
The libfabric 1.7.0 is too old. This branch adopts the latest libfabric v1.12.1. The new libfabric is incorporated with the following new useful features for derecho.
1) The new "tcp" provider replacing deprecated "sockets" provider. It *alleviates* the sequential consistency issue. Cascade is now working with it.
2) The awkward "desc" argument for `fi_write/fi_writemsg` and similar APIs in `fi_rma` module, which has been used to pass memory region keys, is replaced by a solid entity called "descriptor". To get the descriptor, just call `fi_mr_desc()` on a memory region fid.
3) the new v1.12.1 release seems to support GPU Direct, which will be required in Cascade data path enhancement.
@etremel I'm considering including this feature in release r2.2.
> Migrate to libfabric 1.12.1

- include/derecho/core/detail/group_impl.hpp
- include/derecho/core/detail/view_manager.hpp
- include/derecho/core/group.hpp
- include/derecho/persistent/Persistent.hpp
- include/derecho/persistent/detail/FilePersistLog.hpp
- include/derecho/persistent/detail/PersistLog.hpp
- include/derecho/persistent/detail/Persistent_impl.hpp
- src/applications/demos/overlapping_replicated_objects.cpp
- src/applications/demos/signed_store_mockup.cpp
- src/applications/demos/signed_store_mockup.hpp
- src/applications/demos/simple_replicated_objects.cpp
- src/applications/demos/simple_replicated_objects_json.cpp
- src/applications/tests/performance_tests/signed_store_test.cpp
- src/applications/tests/unit_tests/log_restart_test.cpp
- src/applications/tests/unit_tests/signed_log_test.cpp
- src/applications/tests/unit_tests/view_change_test.cpp
- src/core/view_manager.cpp
- src/persistent/FilePersistLog.cpp
- src/persistent/test.cpp
Weijia and I realized that some parts of Derecho would need additional functions in order to get CascadeChain to work the way I want it to. This branch implements those changes. Specifically:
* Persistent<T> has a new `getDeltaSignature<DeltaType>()` method that allows the caller to specify a "search function" that will be called on the delta value that is in the log at the specified version number (similar to the user-provided function in `getDelta<DeltaType>()`). If the search function returns false when called on the delta value, no signature will be returned and `getDeltaSignature` returns false.
* Persistent<T> also has a new `getSignatureByIndex()` method, which helps implement `getDeltaSignature()`
* Group has a new `get_num_subgroups<SubgroupType>()` method, which returns the …
> New APIs needed for CascadeChain

- include/derecho/core/detail/multicast_group.hpp
- include/derecho/core/detail/replicated_impl.hpp
- include/derecho/core/detail/view_manager.hpp
- include/derecho/core/replicated.hpp
- include/derecho/persistent/Persistent.hpp
- include/derecho/persistent/detail/FilePersistLog.hpp
- include/derecho/persistent/detail/PersistLog.hpp
- include/derecho/persistent/detail/Persistent_impl.hpp
- src/core/multicast_group.cpp
- src/core/view_manager.cpp
- src/persistent/FilePersistLog.cpp
Although we expose the stability frontiers by a set of callbacks passed to the Derecho group constructor, application code inside a subgroup type wrapped in `Replicated<T>` also needs access to those frontiers. This patch exposes those frontiers through a set of methods in the group handle available to `Replicated<T>`.
1. `Replicated<T>::get_global_persistence_frontier()`
1. `Replicated<T>::get_global_verified_frontier()`
1. `wait_for_global_persistence_frontier()`
`wait_for_global_verified_frontier()` is left for future, when we really need it. The mechanism should be the same as that of `wait_for_global_persistence_frontier()`.
I've tested it using the Cascade branch [`refactor_get_api`](https://github.com/Derecho-Project/cascade/tree/refactor_get_api) and it works.
> Expose frontiers through Replicated<T>

- include/derecho/core/detail/external_group_impl.hpp
- include/derecho/core/detail/p2p_connection.hpp
- include/derecho/core/detail/p2p_connection_manager.hpp
- include/derecho/core/detail/replicated_impl.hpp
- include/derecho/core/detail/rpc_manager.hpp
- include/derecho/core/external_group.hpp
- src/core/p2p_connection.cpp
- src/core/p2p_connection_manager.cpp
- src/core/rpc_manager.cpp
This is a first step towards solving the thread safety problem identified in #217. P2PConnection now requires callers to specify the message type for get_sendbuffer_ptr, send, and increment_incoming_seq_num, instead of trying to internally keep track of the "last used" type with the instance variables prev_mode and last_type. This fixes the race condition I encountered while testing external-client notifications, though it still doesn't make P2PConnection completely thread-safe.
Since these changes are pretty straightforward, and I tested them to confirm they don't break any existing functionality, I think we should merge them before adding more synchronization to P2PConnection.
> Partial fix for P2PConnection concurrency issues

- include/derecho/mutils-serialization/SerializationSupport.hpp
- src/applications/tests/unit_tests/CMakeLists.txt
- src/applications/tests/unit_tests/deserialize_and_run_test.cpp
- src/core/git_version.cpp
- src/mutils-serialization/SerializationSupport.cpp
This is one possible fix for the issue identified in #204. I changed all of the from_bytes_noalloc functions defined for STL types to have two versions, one "const" and one "non-const", that match the two versions of from_bytes_noalloc declared for ByteRepresentable types. This required some tinkering with the enable_if templates, and the way existing functions call from_bytes_noalloc, to get everything to compile, because the compiler is very pedantic about the difference between `context_ptr<T>` and `context_ptr<const T>`.
I'm not sure if these changes match the original intent of the from_bytes_noalloc API defined for ByteRepresentable types, but at least they solve the problem identified in #204. It is now possible to call `deserialize_and_run` on a function that accepts STL-container …
> Create a consistent API for from_bytes_noalloc functions

- include/derecho/core/detail/external_group_impl.hpp
- include/derecho/core/detail/group_impl.hpp
- include/derecho/core/detail/replicated_impl.hpp
- include/derecho/core/detail/view_manager.hpp
- include/derecho/core/replicated.hpp
- src/applications/tests/unit_tests/external_notification_test.cpp
- src/core/git_version.cpp
- src/core/view_manager.cpp
As Ken reported in an e-mail, an external client that attempts to contact the leader while a group is starting up (awaiting its first adequate view) will cause the group to crash. This happens for two reasons:
1. The await_first_view() method assumes any client that connects to the leader is another replica node starting up, not an external client, so it does not properly handle external client requests the way process_new_sockets() would during normal operation. This means it will either fail or hang when it attempts to read joiner_gms_port and the other ports from the client socket, because external clients don't send this list of ports.
2. The await_first_view() method doesn't catch TCP exceptions that socket operations might throw when it is doing the initial "handshake" of exchanging …
> Improve TCP error handling and external client handling

- include/derecho/core/detail/replicated_impl.hpp
- include/derecho/persistent/Persistent.hpp
- include/derecho/persistent/PersistentInterface.hpp
- include/derecho/persistent/detail/Persistent_impl.hpp
- src/core/git_version.cpp
- src/persistent/Persistent.cpp
Although the implementations of the Persistent<T>::persist() method (in e.g. FilePersistLog) have always returned the version actually persisted, which is sometimes greater than the requested version, the top-level persist method and the PersistentRegistry version did not. This turned out to be a problem for my signatures code, since it meant versions could get persisted without being signed if they were persisted "automatically" within FilePersistLog::persist(). Weijia added logic to return the version actually persisted from Persistent<T> and PersistentRegistry, and I fixed the loop in Replicated<T> to repeat the sign() method if more versions were persisted than initially expected.
> Make Persist return a version

- README.md
The spaces in the existing `README` make the command malformed.
> Fix kernel memory overcommit command syntax

- include/derecho/mutils-serialization/SerializationSupport.hpp
- src/applications/tests/unit_tests/rpc_function_types.cpp
- src/core/git_version.cpp
- src/mutils-serialization/CMakeLists.txt
- src/mutils-serialization/serialization-test.cpp
While attempting to write an RPC function for Cascade that accepted a std::map parameter, I discovered some bugs in the mutils-serialization library. I fixed them in the standalone [mutils-serialization repository](https://github.com/derecho-project/mutils-serialization), where it's easier to test changes that affect only that library. This copies in the changes to the Derecho repository's copy of mutils-serialization, and also pulls in another commit that was somehow only in the standalone repository and not in Derecho's copy.
> Serialization fixes

- include/derecho/core/detail/group_impl.hpp
- include/derecho/core/detail/replicated_impl.hpp
- include/derecho/core/detail/view_manager.hpp
- include/derecho/core/group.hpp
- include/derecho/core/notification.hpp
- include/derecho/core/replicated.hpp
- src/applications/tests/unit_tests/CMakeLists.txt
- src/applications/tests/unit_tests/subgroup_view_callbacks.cpp
- src/core/git_version.cpp
I added a mechanism to deliver new-view callbacks to the user-provided objects that define each subgroup (i.e. the T in a Replicated<T>) so that these objects can react to a view change if they want to. If a user-provided object inherits from GetsViewChangeCallback, and implements a method named `new_view_callback`, that method will be called by ViewManager during the last phase of a view change (along with the other "view upcalls"). The existing `view_upcalls` parameter to the Group constructor can't be used to provide this feature because the user-provided replicated objects are constructed within the Group constructor, and thus don't yet exist at the time you would need to declare a callback function for that parameter.
> Deliver new-view callbacks to replicated objects

- include/derecho/persistent/PersistException.hpp
- include/derecho/persistent/Persistent.hpp
- include/derecho/persistent/detail/FilePersistLog.hpp
- include/derecho/persistent/detail/PersistLog.hpp
- include/derecho/persistent/detail/PersistNoLog_impl.hpp
- include/derecho/persistent/detail/Persistent_impl.hpp
- include/derecho/persistent/detail/util.hpp
- src/applications/archive/persistent_temporal_send_test.cpp
- src/applications/archive/persistent_temporal_stability_test.cpp
- src/applications/archive/volatile_temporal_send_test.cpp
- src/applications/archive/volatile_temporal_stability_test.cpp
- src/applications/archive/volatile_typed_subgroup_bw_test.cpp
- src/applications/tests/performance_tests/persistent_latency_test.cpp
- src/core/git_version.cpp
- src/core/persistence_manager.cpp
- src/persistent/FilePersistLog.cpp
- src/persistent/Persistent.cpp
This is a fix for the weird inconsistency between the rest of Derecho, which throws exceptions derived from std::exception, and Persistent, which throws plain integers that are bit-packed with error codes generated by macros like PERSIST_EXP_INV_VERSION. I created a hierarchy of exception types that derive from std::runtime_error to replace the various macros in PersistException.hpp, trying to reflect the same division of error types that the macros had without creating too many exception classes. I did a basic test with mixed_persistence_test and everything seems to run fine.
> Replace macro-based persistent exceptions with real exceptions

- CMakeLists.txt
- src/conf/CMakeLists.txt
- src/core/git_version.cpp
Attempting to compile Derecho on a Fractus node where the LibFabrics and nlohmann-JSON libraries were not installed system-wide revealed two bugs in our CMake declarations:
1. The Conf module did not declare its dependency on nlohmann_json even though conf.cpp includes nlohmann/json.hpp 
2.  The top-level CMakeLists did not call include_directories() after calling find_package(libfabric), which is necessary for packages that do not export CMake targets (the "old way") - we need to both link `${libfabric_LIBRARIES}` **and** include `${libfabric_INCLUDE_DIRS}`.
> Fix bugs in our CMake dependency declarations

- scripts/prerequisites/install-json.sh
- scripts/prerequisites/install-libfabric.sh
- scripts/prerequisites/install-mutils-containers.sh
- scripts/prerequisites/install-mutils.sh
- src/core/git_version.cpp
According to Linux standards, the /var/tmp directory should be preserved across reboots and should not be deleted frequently by the OS, and many Linux distributions never delete files from /var/tmp. Installers and programs that use /var/tmp are supposed to clean up after themselves and delete the temporary directories they create in /var/tmp. Since our install scripts do not clean up after themselves, the Fractus nodes suffer from an ever-growing number of temporary directories in /var/tmp (each containing copies of libfabric, nlohmann_json, and mutils) that are not deleted automatically.
(See https://superuser.com/questions/168125, https://superuser.com/questions/499039/, and https://unix.stackexchange.com/questions/698677)
> Fix install scripts to remove temp directories

- include/derecho/core/detail/restart_state.hpp
- include/derecho/persistent/detail/PersistNoLog_impl.hpp
- include/derecho/persistent/detail/Persistent_impl.hpp
- include/derecho/sst/sst.hpp
- include/derecho/tcp/tcp.hpp
- src/applications/tests/performance_tests/persistent_latency_test.cpp
- src/applications/tests/performance_tests/typed_subgroup_bw_test.cpp
- src/core/git_version.cpp
- src/core/restart_state.cpp
- src/core/view_manager.cpp
- src/rdmc/lf_helper.cpp
- src/tcp/tcp.cpp
This is a fix for the bug identified in #252. A node that thinks it is not in total-restart mode but gets a TOTAL_RESTART response from the leader will recover from the situation by creating an empty `curr_view` with VID -1, instead of crashing because it attempts to send a null `curr_view` to the leader. The restart leader will ignore this view, since it has an "older" VID than the leader's current view, and treat the new node as a very out-of-date node that was not in the last known view. Thus the new node can't contribute to achieving a restart quorum (which it shouldn't) but it can get added as a new member as soon as the restart finishes.
While fixing this, I realized that the restart leader would also crash when the non-restarting node crashed, because it didn't properly handle the …
> Fix crash in total restart caused by issue #252

- include/derecho/core/detail/group_impl.hpp
- src/core/persistence_manager.cpp
> cleanup procedure change: flush persistent data on leave

- include/derecho/core/detail/derecho_internal.hpp
- include/derecho/core/detail/external_group_impl.hpp
- include/derecho/core/detail/remote_invocable.hpp
- include/derecho/core/detail/replicated_impl.hpp
- include/derecho/core/detail/rpc_manager.hpp
- include/derecho/core/detail/rpc_utils.hpp
- include/derecho/core/external_group.hpp
- include/derecho/core/group.hpp
- src/applications/tests/CMakeLists.txt
- src/applications/tests/performance_tests/bandwidth_test.cpp
- src/applications/tests/performance_tests/deliver_predicate_delay.cpp
- src/applications/tests/performance_tests/latency_test.cpp
- src/applications/tests/performance_tests/multiple_active_subgroups_test.cpp
- src/applications/tests/performance_tests/persistent_bw_test.cpp
- src/applications/tests/performance_tests/sender_delay_test.cpp
- src/applications/tests/performance_tests/signed_bw_test.cpp
- src/applications/tests/performance_tests/signed_store_test.cpp
- src/applications/tests/performance_tests/signed_store_test.hpp
- src/applications/tests/performance_tests/single_active_subgroup_test.cpp
- src/applications/tests/performance_tests/typed_subgroup_bw_test.cpp
- src/applications/tests/scalability_tests/CMakeLists.txt
- src/applications/tests/unit_tests/cooked_send_test.cpp
- src/applications/tests/unit_tests/delivery_order_test.cpp
- src/applications/tests/unit_tests/signed_log_test.cpp
- src/applications/tests/unit_tests/signed_log_test.hpp
- src/core/git_version.cpp
- src/core/multicast_group.cpp
- src/core/rpc_manager.cpp
- src/sst/lf.cpp
I discovered while running regression tests for the Derecho 2.4 release that many of our unit tests had been broken by commit eb5b281a31277faea6dd61649d057fcb094ec941, which disabled global stability callbacks for RPC ("cooked") messages. This change made sense from an API standpoint, since the global stability callback is designed for "raw" messages; it receives a pointer to the delivered byte buffer, but it can't do anything useful with the buffer if it contains serialized RPC function arguments (unless it knows the types of objects to deserialize). However, several of our unit tests that used Replicated Objects with RPC messages were relying on the global stability callback to determine when the test had finished; they ignored the contents of the message in the callback and only looked …
> Fix unit tests that relied on global stability callbacks

- derechoConfig.cmake
- include/derecho/core/detail/derecho_sst.hpp
- include/derecho/core/detail/external_group_impl.hpp
- include/derecho/core/detail/group_impl.hpp
- include/derecho/core/detail/view_manager.hpp
- include/derecho/core/group.hpp
- include/derecho/core/replicated.hpp
- include/derecho/persistent/Persistent.hpp
- include/derecho/persistent/detail/FilePersistLog.hpp
- include/derecho/sst/detail/sst_impl.hpp
- include/derecho/utils/time.h
- src/core/multicast_group.cpp
- src/core/rpc_manager.cpp
- src/core/view_manager.cpp
- src/persistent/FilePersistLog.cpp
- src/sst/lf.cpp
Exposing more group configuration information through GroupProjection. Before, the information was retrieved through `derecho::Conf` API, which loads the information from the configuration file. That's not optimal regarding the source of information. Instead, the active group class should take responsibility. 
The other minor change in the pull request is the removal of PAGE_SIZE definition. Previously, I defined it to `getpagesize()` call. That uses the runtime information. Although it does not cause any issues in most cases, it prevents static/compile-time checking. Instead, PAGE_SIZE should derive from the compile-time detector as a constant. However, Derecho only uses it in the file system log layer, so I removed it here.
> Exposing more information through GroupProjection. Removing PAGE_SIZE macro definition.

- include/derecho/core/detail/replicated_impl.hpp
- include/derecho/core/replicated.hpp
- include/derecho/persistent/HLC.hpp
- src/applications/demos/signed_store_mockup.cpp
- src/applications/tests/performance_tests/signed_store_test.cpp
- src/persistent/HLC.cpp
Previously, the timestamp for each message in a shard is assigned by the sending member. If the members in a shard have drifting clocks, a message with a higher version might have a lower timestamp than another message with a lower version. We call it out-of-order timestamps. Although we manage the timestamp index independently, it would be nice if timestamp and version orders are consistent. Here we borrow the idea of the HLC clock: on message delivery, the current timestamp to assign is checked against the previous one. If the timestamp goes back, we enforce it to be the previous timestamp + 1 using HLC rules. This operation is consistent among all replicas as the message order is guaranteed among them.
> Timestamp order is guaranteed in a shard, even with loosely synchronized clock.

- README.md
- include/derecho/conf/conf.hpp
- include/derecho/core/detail/external_group_impl.hpp
- include/derecho/core/detail/view_manager.hpp
- include/derecho/core/external_group.hpp
- src/applications/archive/initialize.cpp
- src/conf/conf.cpp
- src/conf/derecho-sample.cfg
- src/core/git_version.cpp
- src/core/restart_state.cpp
- src/core/view_manager.cpp
This branch makes two changes aimed at making it easier for nodes to rejoin a group after they crash and restart:
1. Renames the leader_ip and leader_gms_port config options to contact_ip and contact_port, and removes the config option leader_external_port. This reflects existing behavior: Both internal and external clients only need to know the IP and port of any one group member, not the leader, in order to start up and connect.
2. Changes the recover-from-logs procedure so that a restarting node will first attempt to do a "normal" join at the node specified by contact_ip (waiting for half of the configured restart_timeout), before examining the restart_leaders list and deciding if it should act as a restart leader. This allows the node that is configured as the restart leader to …
> Improvements to configuration and restart logic

- include/derecho/mutils-serialization/SerializationSupport.hpp
The in-place deserializer for std::vector (mutils::from_bytes_no_alloc()) has a bug, where the 'const' quialifier needs to be casted off from type T when creating the context_ptr. Otherwise, it's impossible to add entries to it during deserialization. The deserializer for std::map/unordered_map has this correct.
> A bugfix for std::vector deserializer.

- src/applications/demos/oob_rdma.cpp
Two-sided oob rdma tester is buggy. It will crash with verbs RDMA but OK with tcp. However, the API implementation seems correct because DCCL works. This is a minor issue to be solved in the future.
> disabling two sided oob rdma tester.

- src/applications/demos/oob_rdma.cpp
- src/sst/lf.cpp
Derecho OOB transfer now supports CUDA Memory. This has been tested using `src/applications/demos/oob_rdma`. The communication nodes can use GPU memory or host memory independently.
> CUDA SUPPORT

- CMakeLists.txt
- derechoConfig.cmake
- include/derecho/utils/logger.hpp
- src/applications/tests/unit_tests/client_callback_mockup.hpp
The spdlog library introduced some non-backward-compatible changes between version 1.9.2 (packaged with Ubuntu 22.04) and version 1.12 (packaged with Ubuntu 24.04). Specifically, standard library containers are only log-printable if the new header `<spdlog/fmt/ranges.h>` is included, and user-defined types are only log-printable if they explicitly specialize `fmt::formatter<T>`  -- including `<spdlog/fmt/ostr.h>` and defining an `operator<<` for your type, as done in spdlog 1.9.2, is no longer sufficient.
I updated the code to compile against spdlog 1.12, and updated CMakeLists to specify spdlog 1.12 as the new minimum required version, because the header `<spdlog/fmt/ranges.h>` doesn't exist in spdlog 1.9.2. Since this changes Derecho's required dependencies, it should go into a new …
> Upgrade spdlog dependency to 1.12

- README.md
- include/derecho/core/detail/persistence_manager.hpp
- src/conf/CMakeLists.txt
- src/core/persistence_manager.cpp
- src/persistent/Persistent.cpp
The README section on configuration files was out-of-date, and still referred to the old "leader_ip" and "leader_port" options which no longer exist. I fixed it and added an explanation of the new "per-node config" feature (derecho_node.cfg), which was also missing.
Also, I noticed while testing that an assert in persistence_manager could actually fail during correct behavior, because I misunderstood the invariants of persistence requests and persist() calls. It's possible for persisted_version to be less than the parameter version, if the parameter version corresponds to a null message (which does not create a log entry). When a persistence request is posted, the argument version is just the current version at the time the request was posted, not the latest non-null version; thus it's …
> Updated README and removed an erroneous assert

- include/derecho/core/detail/p2p_connection.hpp
- include/derecho/utils/logger.hpp
- src/applications/tests/unit_tests/persistence_notification_test.cpp
- src/core/git_version.cpp
The latest version of spdlog (1.15) depends on a newer version of fmt (11.1) that is slightly pickier about how it finds formatters for some data types (like atomics and enums). This change allows Derecho to compile with spdlog 1.15 while preserving backward compatibility with spdlog 1.12.
> Update spdlog usage to remain compatible with the latest version
